version: '3'

services:
  app:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=development
    depends_on:
      - redis

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data: 